### ISSUE TITLE
Adding CA bank account - Freezing. 

### ISSUE THREAD

**Issue by nickadian** [sharetribe/ftw-daily#1500] opened 2022-03-13 21:52 UTC
When on mobile (tried on iPhone 8 and iPhone 12) if in a new account and adding your first listing. On publish you are prompted to add your banking details. This will not allow you to scroll to the bottom and freezes.

1. Go to 'WetRentals.ca"
2. Click on 'Create account, add listing, ill out details and click publish'
3. Scroll down to 'publish'

**Expected behaviour**  Ability to add bank

**Screenshots** Attached 

**Desktop (please complete the following information):**

- OS: [e.g. iOS] 15.0

**Smartphone (please complete the following information):** 

- Device: iPhone 12
- OS: 15
- Browser Safari and Chrome 
- 

**Additional context** Add any other context about the problem here.

https://user-images.githubusercontent.com/89604665/158080588-0a5d69d4-a5ad-4270-b73a-2095f1bd6e41.mp4

**Comment by nickadian** [comment] 2022-03-13 22:58
Verified across multiple flex sites including fresh install. Other example https://www.localtrailerhire.com.au/

**Comment by Gnito** [comment] 2022-03-15 13:07
Hi @nickadian,
and thanks for reporting!

I'm not entirely sure what has caused this regression, but it seems to be related to the fact that 100vh is not constant on mobile safari. The height of the viewport changes, when the browser's top&bottom bars reduce their height when scrolling. 

So, it might even be that rendering logic has changed, when Safari moved the location bar - or that the issue has become more prominent at that point.

One way to make the button visible on the actually scrollable area is to add padding-bottom for the StripeConnectAccountForm on EditListingWizard.

https://github.com/sharetribe/ftw-daily/blob/master/src/components/EditListingWizard/EditListingWizard.js#L423
```diff
+                  className={css.stripeConnectAccountForm}
```

And then adding that class to EditListingWizard.module.css

```
.stripeConnectAccountForm {
  padding-bottom: 120px;
}
```

This is probably what I'm going to add to this template, but I'll try to check first if something reasonable could be done to the actual height of the modal container.

**Comment by nickadian** [comment] 2022-03-15 14:47
Thats perfect, it seems to work. It does freeze the page while typing in the account numbers but that is functional. I was able to save a test account no problem. 

thank you!

**Comment by nickadian** [comment] 2022-03-15 15:43
Once you click on the bank account and back out, it freezes to this frame. See the quick video :) 


https://user-images.githubusercontent.com/89604665/158415843-87edbbe8-8381-416c-bac6-7dcaca1302e3.mp4

**Comment by Gnito** [comment] 2022-03-15 15:49
@nickadian Could you try that 1501 approach to check if it helps?

**Comment by nickadian** [comment] 2022-03-15 15:49
You bet, ill have it done in 5 min

**Comment by nickadian** [comment] 2022-03-15 16:02
Worked great on mobile, but getting a hard error on web

![image](https://user-images.githubusercontent.com/89604665/158420048-212b62c1-6aea-483d-bc83-614f755ce33a.png)

**Comment by nickadian** [comment] 2022-03-15 16:02
The error is across the board

**Comment by Gnito** [comment] 2022-03-15 16:17
Uh, sorry. I was a bit too eager to share this and didn't test it with `yarn run dev-server`.

The problem is SSR: "window" is not defined on Node.js environment.
Therefore, the constructor of ModalComponent should just have `this.vh = null;` 
(instead of `this.vh = window.innerHeight * 0.01;`)

**Comment by Gnito** [comment] 2022-03-16 14:30
Yes.

I also added `position: absolute;` to isOpenInPortal class + couple of other commits to fix some issues I noticed on booking panel.

> Note: modal in BookingPanel still shows the extra-space problem with 100vh (since it uses ModalInMobile setup), but it's not preventing the usage, which was the case in EditListingWizard. I didn't start refactoring that modal, since it needs bigger changes (and definitely more cross-browser testing) to be used through React Portals.

**Comment by Gnito** [comment] 2022-03-16 16:16
The fix is now merged to master. I'm closing this issue for now.
#1501

**Closed by Gnito** 2022-03-16 16:16 UTC

**Comment by nickadian** [comment] 2022-03-16 16:34
Tested and looks/ works great!
